### ISSUE TITLE
hidden form html can be added to any html file

### ISSUE THREAD

**Issue by fool** [kimfucious/netlify-forms-formik#1]
This is kind of pedantic, so feel free to ignore it!   But, you asked for feedback ;)

You reference in a few places the need to add the form to `/public/index.html` but as you say later, it could be any html file that ends up in /public, not necessarily that one.  I can confirm that will work :)

However, I couldn't come up with a concise way to say all of that myself, compared to your example, so I don't have a good suggestion that isn't cumbersome.  And it does totally work as you wrote so there's not  a strong *need* to change.

Thanks again for writing this up!

**Comment by kimfucious** [comment]
Hi Chris @fool 

It was a pleasure to write this up, as it lit a few light bulbs that needed lighting in my head.

I've updated the readme file, per your comments here, to hopefully clarify that a form block in a separate HTML file should do the trick as an alternative to directly editing the `/public/index.html` file.

Feel free to suggest any other improvements to this write up, should you see something that could be improved.

Best,

Kim
